In [2]:
import numpy as np


In [3]:
# From Python Lists

In [4]:
arr = np.array([1, 2, 3])


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])



In [6]:
# Special Arrays


In [7]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.rand(3, 2)

array([[0.71480591, 0.63246914],
       [0.27764074, 0.39468449],
       [0.19810106, 0.82887209]])

In [13]:
np.random.randn(3, 2)

array([[-2.40844046,  0.44730529],
       [ 0.50182316, -1.47498498],
       [-0.48120186, -1.59718313]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
print(arr.shape)

(2, 3)


In [16]:

print(arr.ndim)

2


In [17]:
print(arr.size)

6


In [18]:
print(arr.dtype)

int64


In [19]:
a = np.array([1, 2, 3])

In [20]:
b = np.array([4, 5, 6])

In [21]:
a + b

array([5, 7, 9])

In [22]:
a * b

array([ 4, 10, 18])

In [23]:

np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [24]:
A = np.array([[1, 2], [3, 4]])

In [25]:
B = np.array([[5, 6], [7, 8]])

In [26]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [27]:
A @ B

array([[19, 22],
       [43, 50]])

In [28]:
arr = np.array([1, 2, 3, 4])

In [29]:
arr.sum()

np.int64(10)

In [30]:
arr.mean()

np.float64(2.5)

In [31]:
arr.max()

np.int64(4)

In [32]:
arr.min()

np.int64(1)

In [33]:
arr.std()

np.float64(1.118033988749895)

In [34]:
arr = np.array([1, 2, 3, 4, 5])

In [35]:


arr[0]

np.int64(1)

In [36]:
arr[1:4]

array([2, 3, 4])

In [37]:
arr[::2]

array([1, 3, 5])

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
arr[0, 1]

np.int64(2)

In [40]:
arr[:, 1]

array([2, 5])

In [41]:
arr[1, :2]

array([4, 5])

In [42]:
arr = np.array([1, 2, 3, 4, 5])

In [43]:
mask = arr >3

In [44]:
arr[mask]

array([4, 5])

In [45]:
arr = np.arange(6)

In [46]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
a = np.array([1, 2])

In [48]:
b = np.array([3, 4])

In [49]:
np.concatenate((a, b))

array([1, 2, 3, 4])

In [50]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [51]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [52]:
a = np.array([1, 2, 3])

In [53]:
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [54]:
np.save('array.npy', arr)

In [55]:
loaded_arr = np.load('array.npy')